import { avaterImage } from "./Images";

export const settings = [
    {
        "name":"修改昵称",
        "text":"bql",
        "image":""
    },
    {
        "name":"更换头像",
        "text":"",
        "image":avaterImage
    },
    {
        "name":"字体大小",
        "text":"14",
        "image":""
    },
    {
        "name":"主题模式",
        "text":"浅色",
        "image":""
    },
    {
        "name":"用户帮助",
        "text":"",
        "image":""
    },
    {
        "name":"反馈建议",
        "text":"",
        "image":""
    },
    {
        "name":"用户协议",
        "text":"",
        "image":""
    },
    {
        "name":"注销账户",
        "text":"",
        "image":""
    },
    {
        "name":"活动日志",
        "text":"",
        "image":""
    },
]
